### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by krouzbeh** [igloo15/slideshow-card#5]
I get: no card type configured

- type: custom:slideshow-card
  arrow_color: var(--primary-text-color)
  arrow_opacity: 0.5
  cards:
    - type: picture
      image: /local/images/1.jpg

**Comment by harambe88** [comment]
Similar here: I'm getting "Custom element doesn't exist: slideshow-card"

**Comment by krouzbeh** [comment]
I'm getting this error on the UI card randomly => "element.setConfig is not a function"

```
type: custom:slideshow-card
flush: true
arrow_color: White
arrow_opacity: 0.5
auto_play: true
auto_delay: 4
style:
  border-radius: 25px
cards:
  - type: picture
    image: /local/images/1.jpg
  - type: picture
    image: /local/images/2.jpg
  - type: picture
    image: /local/images/3.jpg
```
